name: demo-postgres
services:
  db:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpassword}
      POSTGRES_DB: ${POSTGRES_DB:-pgdatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
volumes:
  postgres_data: 