FROM debian:12-slim AS ansible-controller

RUN apt-get update && apt-get install -y \
    ansible \
    sshpass \
    openssh-client

COPY ansible-setup /ansible-setup
WORKDIR /ansible-setup

CMD ["tail", "-f", "/dev/null"]